version: '3.8'

services:
  django-web:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    container_name: django-docker
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./frontend/build:/app/frontend/build
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    env_file:
      - .env

  react-app:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: react-app
    depends_on:
      - django-web
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend/
      - /app/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
